import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Zap, AlertTriangle, Shield } from 'lucide-react';
import type { SecurityEvent } from '../lib/supabaseClient';

interface AIInsightModalProps {
    event: SecurityEvent | null;
    onClose: () => void;
}

export function AIInsightModal({ event, onClose }: AIInsightModalProps) {
    const [displayText, setDisplayText] = useState('');
    const [isTyping, setIsTyping] = useState(false);

    // Generate AI insight text (mock - replace with Azure OpenAI call)
    const generateInsight = (event: SecurityEvent): string => {
        const insights: Record<string, string> = {
            critical: `🔴 CRITICAL THREAT ANALYSIS\n\nThis event represents a severe security incident requiring immediate attention.\n\nAgent ${event.agent_id} has detected: ${event.event_type}\n\n📋 Assessment:\nThe behavioral patterns suggest a sophisticated attack vector. The system has automatically engaged defensive protocols.\n\n🛡️ Recommended Actions:\n1. Isolate the affected endpoint immediately\n2. Review access logs for the past 24 hours\n3. Initiate a full system scan\n4. Consider activating Global Lockdown if pattern spreads\n\n⚡ This analysis was generated by Vanguard AI Sentinel.`,
            high: `🟠 HIGH PRIORITY ALERT\n\nSignificant anomaly detected at Agent ${event.agent_id}.\n\nEvent Type: ${event.event_type}\n\n📋 Assessment:\nThis activity deviates from established behavioral baselines. While not immediately critical, it warrants close monitoring.\n\n🛡️ Recommended Actions:\n1. Monitor the endpoint for the next 30 minutes\n2. Check for additional correlated events\n3. Prepare rollback snapshot if needed\n\n⚡ Vanguard AI Sentinel - Protecting your perimeter.`,
            medium: `🟡 MODERATE CONCERN\n\nAgent ${event.agent_id} has flagged a potential issue.\n\nEvent: ${event.event_type}\n\n📋 Assessment:\nThis appears to be a minor deviation that could indicate early-stage reconnaissance or a false positive.\n\n🛡️ Recommended Actions:\n1. Log the event for trend analysis\n2. No immediate action required\n3. Review during next security audit\n\n⚡ Vanguard AI - Always vigilant.`,
            low: `🟢 INFORMATIONAL\n\nRoutine event logged by Agent ${event.agent_id}.\n\nType: ${event.event_type}\n\nThis is a standard operational log entry. No action required.\n\n⚡ Vanguard AI - Your silent guardian.`
        };

        return insights[event.severity] || insights.low;
    };

    // Typewriter effect
    useEffect(() => {
        if (!event) {
            setDisplayText('');
            return;
        }

        setIsTyping(true);
        setDisplayText('');
        const fullText = generateInsight(event);
        let index = 0;

        const typeInterval = setInterval(() => {
            if (index < fullText.length) {
                setDisplayText(fullText.slice(0, index + 1));
                index++;
            } else {
                setIsTyping(false);
                clearInterval(typeInterval);
            }
        }, 15);

        return () => clearInterval(typeInterval);
    }, [event]);

    return (
        <AnimatePresence>
            {event && (
                <motion.div
                    className="modal-overlay"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    onClick={onClose}
                >
                    <motion.div
                        className="ai-insight-modal"
                        initial={{ opacity: 0, scale: 0.9, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.9, y: 20 }}
                        onClick={(e) => e.stopPropagation()}
                    >
                        {/* Modal Header */}
                        <div className="modal-header">
                            <div className="modal-title">
                                <Zap size={24} className="ai-icon" />
                                <h2>AI Threat Analysis</h2>
                            </div>
                            <motion.button
                                className="close-btn"
                                onClick={onClose}
                                whileHover={{ scale: 1.1 }}
                                whileTap={{ scale: 0.9 }}
                            >
                                <X size={20} />
                            </motion.button>
                        </div>

                        {/* Event Summary */}
                        <div className={`event-summary severity-${event.severity}`}>
                            <div className="summary-icon">
                                {event.severity === 'critical' || event.severity === 'high' ? (
                                    <AlertTriangle size={20} />
                                ) : (
                                    <Shield size={20} />
                                )}
                            </div>
                            <div className="summary-text">
                                <span className="event-type">{event.event_type}</span>
                                <span className="event-severity">{event.severity.toUpperCase()}</span>
                            </div>
                        </div>

                        {/* AI Insight Content */}
                        <div className="insight-content">
                            <pre className="typewriter-text">
                                {displayText}
                                {isTyping && <span className="cursor">▊</span>}
                            </pre>
                        </div>

                        {/* Action Buttons */}
                        <div className="modal-actions">
                            <motion.button
                                className="action-btn secondary"
                                onClick={onClose}
                                whileHover={{ scale: 1.02 }}
                                whileTap={{ scale: 0.98 }}
                            >
                                Dismiss
                            </motion.button>
                            <motion.button
                                className="action-btn primary"
                                whileHover={{ scale: 1.02 }}
                                whileTap={{ scale: 0.98 }}
                            >
                                <Shield size={16} />
                                Take Action
                            </motion.button>
                        </div>
                    </motion.div>
                </motion.div>
            )}
        </AnimatePresence>
    );
}
